<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE accident-report [
<!ELEMENT accident-report (accident-unit)>
<!ELEMENT accident-unit (person-involved, accident-info, abstract)>

<!ELEMENT person-involved (family-name, first-name, age, gender, position)>
<!ELEMENT family-name (#PCDATA)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT position (#PCDATA)>

<!ELEMENT accident-info (occuring-date, situation, type)>

<!ELEMENT occuring-date (year, month, date, time)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT time (#PCDATA)>

<!ELEMENT situation (#PCDATA)>
<!ELEMENT type (#PCDATA)>

<!ELEMENT abstract (#PCDATA)>
]>
<accident-report>
	<accident-unit>
		<person-involved>
			<family-name>荒川</family-name>
			<first-name>幸助</first-name>
			<age>33</age>
			<gender>1</gender>
			<position>3</position>
		</person-involved>
		
		<accident-info>
			<occuring-date>
				<year>2022</year>
				<month>1</month>
				<date>24</date>
				<time>11</time>
			</occuring-date>
			<situation>2</situation>
			<type>6</type>
		</accident-info>
		
		<abstract>
			物を落として手を切った。
		</abstract>
	</accident-unit>
</accident-report>
