<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE accident-report [
<!ELEMENT accident-report (accident-unit)>
<!ELEMENT accident-unit (person-involved, accident-info, abstract)>

<!ELEMENT person-involved (family-name, first-name, age, gender, position)>
<!ELEMENT family-name (#PCDATA)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT position (#PCDATA)>

<!ELEMENT accident-info (occuring-date, situation, type)>

<!ELEMENT occuring-date (year, month, date, time)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT time (#PCDATA)>

<!ELEMENT situation (#PCDATA)>
<!ELEMENT type (#PCDATA)>

<!ELEMENT abstract (#PCDATA)>
]>
<accident-report>
	<accident-unit>
		<person-involved>
			<family-name></family-name>
			<first-name></first-name>
			<age></age>
			<gender></gender>
			<position></position>
		</person-involved>
		
		<accident-info>
			<occuring-date>
				<year></year>
				<month></month>
				<date></date>
				<time></time>
			</occuring-date>
			<situation></situation>
			<type></type>
		</accident-info>
		
		<abstract></abstract>
	</accident-unit>
</accident-report>
