<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE accident-report [
<!ELEMENT accident-report (accident-unit)>
<!ELEMENT accident-unit (person-involved, accident-info, abstract)>

<!ELEMENT person-involved (family-name, first-name, age, gender, position)>
<!ELEMENT family-name (#PCDATA)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT gender (#PCDATA)>
<!ELEMENT position (#PCDATA)>

<!ELEMENT accident-info (occuring-date, situation, type)>

<!ELEMENT occuring-date (year, month, date, time)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT month (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT time (#PCDATA)>

<!ELEMENT situation (#PCDATA)>
<!ELEMENT type (#PCDATA)>

<!ELEMENT abstract (#PCDATA)>
]>
<accident-report>
	<accident-unit>
		<person-involved>
			<family-name>田中</family-name>
			<first-name>太郎</first-name>
			<age>19</age>
			<gender>1</gender>
			<position>1</position>
		</person-involved>
		
		<accident-info>
			<occuring-date>
				<year>2022</year>
				<month>1</month>
				<date>17</date>
				<time>13</time>
			</occuring-date>
			<situation>1</situation>
			<type>2</type>
		</accident-info>
		
		<abstract>
			実験中に手が滑り、持っていたフラスコを割ってしまった。割った際にガラスで足を切った。薬剤は入っていなかったため、ガラスの片づけのみを行ったのち、保健管理室にて手当を受けた。
		</abstract>
	</accident-unit>
</accident-report>
